### ISSUE TITLE
weird jump when getting out of a modal window

### ISSUE THREAD

**Issue by akabakass** [plax-00/endscroll.nvim#3]
I've noticed it with the [global-note](https://github.com/backdround/global-note.nvim) plugin, which I use a lot, but it does the same with the Mason or Lazy windows.
Basically, when I am near the bottom of the page but endscroll has not triggered yet because I've not hit the down key more,
If I open one of the mentioned window (:Lazy for example), when I close that overlayed window, the code jump suddenly to the top of the screen.
so from that:
![image](https://github.com/user-attachments/assets/66013114-7d22-4004-836f-d489083caf04)
I open lazy:
![image](https://github.com/user-attachments/assets/97ca286f-68cc-494c-8efa-b9aa7acd277f)
then quit using q
![image](https://github.com/user-attachments/assets/2c51f9e7-7cae-4dbe-93c0-d1f544fba496)
Please let me know if you need more info

**Comment by plax-00** [comment]
Hi, this should fix it. Closing for now but let me know if you're still having issues.

**Comment by akabakass** [comment]
perfect, thx
